# Bagging

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
from sklearn.metrics import accuracy_score
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB


In [18]:
dataset = pd.read_csv('C:/Users/hassa/OneDrive/Desktop/VI sem/ML/lab-external/dataset/Logistic_Iris.csv')

In [20]:
dataset.head

<bound method NDFrame.head of      Sepal Length  Sepal Width  Petal Length  Peatal Width         Species
0             5.1          3.5           1.4           0.2     Iris-setosa
1             4.9          3.0           1.4           0.2     Iris-setosa
2             4.7          3.2           1.3           0.2     Iris-setosa
3             4.6          3.1           1.5           0.2     Iris-setosa
4             5.0          3.6           1.4           0.2     Iris-setosa
..            ...          ...           ...           ...             ...
145           6.7          3.0           5.2           2.3  Iris-virginica
146           6.3          2.5           5.0           1.9  Iris-virginica
147           6.5          3.0           5.2           2.0  Iris-virginica
148           6.2          3.4           5.4           2.3  Iris-virginica
149           5.9          3.0           5.1           1.8  Iris-virginica

[150 rows x 5 columns]>

## Input as x

In [21]:
x = dataset.iloc[:, [0, 1, 2, 3]].values

In [22]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Target is the species. Calling it as y

In [23]:
y = dataset.iloc[:, 4].values


In [24]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## Splitting the dataset into Training and Test Set

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)


# Fitting the training set on the GaussianNB()

In [29]:
Single = GaussianNB()
Single.fit(x_train, y_train)

GaussianNB()

In [32]:
y_pred = Single.predict(x_test)
print('Predicted values for Single Naive Bayes Classifier: ', y_pred)

Predicted values for Single Naive Bayes Classifier:  ['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor']


In [33]:
Acc_Single = accuracy_score(y_test, y_pred) * 100
print('\n\n The Accuracy using Single Naive Bayes Classifier is: ', Acc_Single)



 The Accuracy using Single Naive Bayes Classifier is:  100.0


## Confusion Matrix

In [34]:
cm = confusion_matrix(y_test, y_pred)
print('\n\n Confusion Matix Using Single Naive Bayes Classifier: \n', cm)



 Confusion Matix Using Single Naive Bayes Classifier: 
 [[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


## Initialize the base classifier

In [36]:
base_cls = GaussianNB()

## Number of base classifiers

In [37]:
num_class = 100

## Bagging Classifier

In [38]:
Bag = BaggingClassifier(base_estimator = base_cls, n_estimators = num_class, random_state=0)

## Fitting training data on bagging classifier

In [39]:
Bag.fit(x_train, y_train)

BaggingClassifier(base_estimator=GaussianNB(), n_estimators=100, random_state=0)

## Accuracy using Bagging Classifier

In [42]:
results = model_selection.cross_val_score(Bag, x_test, y_test, cv = 10)

print('\n\n Accuracy using Bagged set of Naive Bayes Classifiers is: ', results.mean()*100)

C:\Users\hassa\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(




 Accuracy using Bagged set of Naive Bayes Classifiers is:  94.16666666666667
